# Dockerfile para o Servidor Broker TCP do Chat Corporativo (UFMT-SD)
FROM maven:3.9-eclipse-temurin-17-alpine AS builder

WORKDIR /app
COPY pom.xml .
COPY src ./src

# Compilar o código-fonte do projeto
RUN mvn compile

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/classes /app/classes

EXPOSE 9090

ENTRYPOINT ["java", "-cp", "/app/classes", "br.ufmt.sd.chat.server.ServerMain"]
