services:
  # Servidor Broker TCP Central (Protocolo OSGURI)
  chat-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: chat-server-broker
    ports:
      - "9090:9090"
    networks:
      - fed-chat-network
    restart: unless-stopped

  # Cliente Web Thymeleaf (Spring Boot)
  chat-web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: chat-web-interface
    ports:
      - "8080:8080"
    environment:
      - CHAT_SERVER_HOST=chat-server
      - CHAT_SERVER_PORT=9090
    depends_on:
      - chat-server
    networks:
      - fed-chat-network
    restart: unless-stopped

networks:
  fed-chat-network:
    driver: bridge
