# Dockerfile para o Cliente Web Spring Boot + Thymeleaf (UFMT-SD)
FROM maven:3.9-eclipse-temurin-17-alpine AS builder

WORKDIR /app
COPY pom.xml .
COPY src ./src

# Compilar o pacote jar Spring Boot
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar /app/chat-web.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/chat-web.jar"]
